// Q1 

let temperature = 21 ;

if (temperature < 18) {
  console.log("It's too cold, turn on the heater");
} else if (18 < temperature < 25) {
  console.log("The temperature is comfortable");
} else if (temperature > 25) {
    console.log("It's too hot, turn on the fan");
 }


// Q2

let score = 49;
if (score >= 90) {
  console.log("Grade A");
} else if (score>=75 && score<89) {
  console.log("Grade B");
} else if (score>=50 && score<74) {
  console.log("Grade C");
} else if ( score < 50) {
  console.log("Grade D");
}



// Q3

let light = "red";

if (light === "red" ) {
  console.log("stop")
} else if (light == "green") {
  console.log("go")
} else if (light == "yellow") {
  console.log ("Slow down")
}



// Q4

let bill = 70;
if (bill <= 50 ) {
  console.log("no discount.")
} else if (bill >= 50 && bill <= 100) {
  console.log("give a 10% discount.")
} else if (bill >= 100) {
  console.log("give a 20% discount.")
}



// Q5


let time = 8
if (time < 7) {
  console.log("It's too early, sleep a bit more.")
} else if (time >= 7 && time < 10) {
  console.log("Time for breakfast and morning exercise.")
} else if (time >= 10 && time < 18) {
  console.log ("Time to work or study.")
} else {
  console.log ("Relax for the day.")
}

// Q6

let temperature1 = 32°C;